changelog:
  categories:
    - title: ⚠️ Breaking changes
      labels:
        - breaking-changes
    - title: Enhancements
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Other changes
      labels:
        - "*"