
// This file is automatically generated by 'yarn build:examples:refresh'.
// Warning: Any manual changes will be lost.

export { default as Heading__heading_exceeding_h6 } from "./components/Heading/examples/heading-exceeding-h6"
export { default as Heading__heading_relative_to_context } from "./components/Heading/examples/heading-relative-to-context"
export { default as Heading__heading_root_context } from "./components/Heading/examples/heading-root-context"
export { default as Heading__heading_with_section_scopes } from "./components/Heading/examples/heading-with-section-scopes"
export { default as Highlight__paragraph_with_highlight } from "./components/Highlight/examples/paragraph-with-highlight"
