name: Build Release

on:
  push:
    branches:
      - create/release

env:
  BRANCH_NAME: ${{ env.GITHUB_REF }}

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get version from package.json
        id: get-version
        run: echo "::set-env name=PACKAGE_VERSION::$(jq -r '.version' package.json)"
        
      - name: Get current version from main branch
        id: get-current-version
        run: echo "::set-env name=CURRENT_VERSION::$(curl -s https://raw.githubusercontent.com/ONSdigital/design-system-react/main/package.json | jq -r '.version')"
        
      - name: Compare versions
        if: env.PACKAGE_VERSION == env.CURRENT_VERSION
        run: exit 1
        env:
          ERROR_MESSAGE: "Package version is the same as HEAD."
        
      - name: Replace version in readme.md
        run: sed -i "s/\(https:\/\/github.com\/ONSdigital\/design-system-react#\)v[0-9]\.[0-9]\.[0-9]/\1${{ env.PACKAGE_VERSION }}/g" README.md
        
      - name: Run yarn build-package
        run: yarn build-package
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build package for ${{ env.PACKAGE_VERSION }}"
          push: true
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          title: "Create release - v${{ env.PACKAGE_VERSION }}"
          body: "This PR includes changes for the release v${{ env.PACKAGE_VERSION }}."
          labels: "release"
          head: ${{ env.BRANCH_NAME }}
          base: main
