name: Create release PR

on:
  push:
    branches:
      - create/release

jobs:
  create_release_pr:
    needs: build_package
    if: contains(github.event.head_commit.message, 'Build release')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Create release PR"
        branch: create/release
        base: main
        title: github.event.head_commit.message
        labels: "release"
