name: Release

on:
  pull_request:
    types: [opened]

env:
  PR_TITLE: "${{ github.event.pull_request.title }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR title
      if: startsWith(env.PR_TITLE, 'Release - v')
      run: |
        echo "PR title is valid"
        pr_version=$(echo "${{ env.PR_TITLE }}" | grep -Eo 'v[0-9]+\\.[0-9]+\\.[0-9]+')
        echo "Extracted version: $pr_version"

    - name: Update version in package.json
      run: |
        echo "Updating version in package.json"
        sed -i.bak "s/\"version\": \"[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+\"/\"version\": \"$pr_version\"/g" package.json

    - name: Update version in README.md
      run: |
        echo "Updating version in README.md"
        sed -i.bak "s/https:\/\/github.com\/ONSdigital\/design-system-react#v[0-9]\\+\\.[0-9]\\+\\.[0-9]\\+/https:\/\/github.com\/ONSdigital\/design-system-react#v$pr_version/g" README.md

    - name: Run build command
      run: yarn build-package

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
        force: true
