name: Release

on:
  pull_request:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR title starts with "Create release:"
      if: startsWith(github.event.pull_request.title, 'Create release:')
      run: echo "PR title starts with 'Create release:', proceeding with update"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get version from PR title
      run: echo "$(echo "${{ github.event.pull_request.title }}" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')"
      id: version

    - name: Update package.json with new version
      run: |
        sed -i "s/\"version\".*/\"version\": \"${{ steps.version.output }}\"/" package.json
        git diff

    - name: Update README with new version
      run: |
        sed -i "s/\/onsdigital\/design-system-react#.*/\/onsdigital\/design-system-react#${{ steps.version.output }}/" README.md
        git diff

    - name: Run build command
      run: yarn build-package

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git add .
        git commit -m "Update version to ${{ steps.version.output }}"

    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ env.GITHUB_TOKEN }}