name: Update Version

on:
  pull_request:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR title starts with "Release -"
      if: startsWith(github.event.pull_request.title, 'Release -')
      run: echo "PR title starts with 'Release -', proceeding with update"
      env:
        pr_version: "${{ (github.event.pull_request.title =~ /v[0-9]+\\.[0-9]+\\.[0-9]+/).captures[0] }}"

    - name: Checkout code
      if: env.pr_version
      uses: actions/checkout@v2

    - name: Update package.json with new version
      if: env.pr_version
      run: |
        sed -i "s/\"version\".*/\"version\": \"${{ env.pr_version }}\"/" package.json
        git diff

    - name: Update README with new version
      if: env.pr_version
      run: |
        sed -i "s/\/ONSdigital\/design-system-react#.*/\/ONSdigital\/design-system-react#${{ env.pr_version }}/" README.md
        git diff

    - name: Run build command
      if: env.pr_version
      run: yarn build-package

    - name: Commit changes
      if: env.pr_version
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
        git add .
        git commit -m "Update version to ${{ env.pr_version }}"

    - name: Push changes
      if: env.pr_version
      uses: ad-m/github-push-action@v1.0.0
      with:
        github_token: ${{ env.GITHUB_TOKEN }}